name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # هذا يخبر GitHub أن يعمل عند أي تحديث لفرع main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # هذا توقيع داخلي تلقائي من GitHub ولا يحتاج منك إدخال أي مفاتيح
          publish_dir: .  # يقوم بنشر الملفات الموجودة في المجلد الرئيسي (حيث يوجد index.html)
